/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 10;
  int ABSTRACT = 14;
  int BOOLEAN = 15;
  int CHAR = 16;
  int CLASS = 17;
  int ELSE = 18;
  int EXTENDS = 19;
  int FALSE = 20;
  int IF = 21;
  int IMPORT = 22;
  int INSTANCEOF = 23;
  int INT = 24;
  int NEW = 25;
  int NULL = 26;
  int PACKAGE = 27;
  int PRIVATE = 28;
  int PROTECTED = 29;
  int PUBLIC = 30;
  int RETURN = 31;
  int STATIC = 32;
  int SUPER = 33;
  int THIS = 34;
  int TRUE = 35;
  int VOID = 36;
  int WHILE = 37;
  int FINAL = 38;
  int FOR = 39;
  int PLUS = 40;
  int ASSIGN = 41;
  int DEC = 42;
  int EQUAL = 43;
  int GT = 44;
  int INC = 45;
  int LAND = 46;
  int LE = 47;
  int LNOT = 48;
  int QM = 49;
  int MINUS = 50;
  int PLUS_ASSIGN = 51;
  int STAR = 52;
  int LPAREN = 53;
  int RPAREN = 54;
  int LCURLY = 55;
  int RCURLY = 56;
  int LBRACK = 57;
  int RBRACK = 58;
  int SEMI = 59;
  int COLON = 60;
  int COMMA = 61;
  int DOT = 62;
  int IDENTIFIER = 63;
  int LETTER = 64;
  int DIGIT = 65;
  int NON_ZERO_DIGIT = 66;
  int INT_LITERAL = 67;
  int CHAR_LITERAL = 68;
  int STRING_LITERAL = 69;
  int ESC = 70;
  int ERROR = 71;

  int DEFAULT = 0;
  int COMMENT = 1;
  int MLCOMMENTS = 2;

  String[] tokenImage = {
    "<EOF>",
    "\"(*\"",
    "\"(*\"",
    "\"*)\"",
    "<token of kind 4>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 13>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"final\"",
    "\"for\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"?\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
